### ISSUE TITLE
ESC and Servo 

### ISSUE THREAD

**Issue by zye1996** [prl-mushr/mushr#23]
Hi there, it is a great project and I do appreciate what you have done! I am wondering if there are specific reasons that you are not using the ESC and servo coming with the car?

**Comment by schmittlema** [comment]
Hi @zye1996 would you mind reposting this in our forum? https://github.com/prl-mushr/mushr/discussions

Happy to answer your question there where others may also be wondering the same thing!

**Comment by zye1996** [comment]
no problem!
