### ISSUE TITLE
small error in repos.yaml

### ISSUE THREAD

**Issue by naughtyStark** [prl-mushr/mushr#5]
when I execute
`vcs import < repos.yaml
`
It throws this error : 
`=== ./range_libc (git) ===
Could not checkout ref 'master': error: pathspec 'master' did not match any file(s) known to git.
`
Apparently the github repository ( https://github.com/kctess5/range_libc ) has no branch by the name of "master" (maybe they changed it?) 
The fix is really simple, in the repos.yaml, simply change the "version" of rangelib_c to "deploy".

Also, people that are new to github or haven't used ssh before should be told to first get an ssh key before running that command (I got stuck there for about an hour before I realized what the problem was).

Thanks.

**Comment by mikehpark927** [comment]
I definitely agree about the ssh key. I think most people are used to cloning with HTTPS and doesn't know how to set up the ssh key, so instructions on that would be useful to new users.

**Comment by naughtyStark** [comment]
Cool :), I'll be closing this issue then.
