### ISSUE TITLE
Instructions do not provide login information for pre-built image

### ISSUE THREAD

**Issue by zlite** [prl-mushr/mushr#8]
The hardware build instructions [here ](https://mushr.io/hardware/build_instructions/#software-setup) show how to use a pre-built image, but do not give the login details for that install. I found them elsewhere, in the simulation tutorial: "The username is robot and the password is prl_robot"

**Comment by schmittlema** [comment]
Fixed [here](https://github.com/prl-mushr/mushr-website/commit/006c9cfdce36e7c5b8ac18b55da266076cb112e8). Appologies for the delay.
